name: clusterone
channels: !!python/tuple
- !!python/unicode
  'defaults'
- !!python/unicode
  'auto'
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'omnia'
- !!python/unicode
  'rdkit'
- !!python/unicode
  'deepchem' 
dependencies:
- h5py=2.7.1
- pandas=0.22.0
- rdkit=2017.09.1
- numpy=1.13.3
- boost=1.63.0
- joblib=0.11
- scikit-learn=0.18.1
- six=1.11.0
- mdtraj=1.9.1
- deepchem=2.0.0
- clusterone=0.10.9
- pdbfixer=1.4
- networkx=2.1
- pillow=5.0.0
- nose=1.3.7
- nose-timer=0.7.0
- flaky=3.3.0
- zlib=1.2.11
- requests=2.18.4
- xgboost=0.6a2
- simdna=0.4.2
- jupyter=1.0.0
- pbr=4.0.4
- setuptools=39.1.0