name: clusterone
channels: !!python/tuple
- !!python/unicode
  'defaults'
- !!python/unicode
  'auto'
- !!python/unicode
  'conda-forge'
dependencies:
- h5py
- pandas
- rdkit
- numpy
- boost
- joblib
- scikit-learn
- six
- mdtraj
- deepchem
- clusterone